# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'InvoiceManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InvoiceManager
  pod 'Charts'
  pod 'TOPasscodeViewController'
  pod 'Locksmith'
  target 'InvoiceManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
